### ISSUE TITLE
Transform.Copy is broken

### ISSUE THREAD

**Issue by puyawsiht** [dradtke/go-allegro#15]
`al_copy_transform` is wrapped like this:  

    // Makes a copy of a transformation.
    func (t *Transform) Copy() *Transform {
    	var dest C.ALLEGRO_TRANSFORM
    	C.al_copy_transform((*C.ALLEGRO_TRANSFORM)(t), &dest)
    	return (*Transform)(&dest)
    }

However the first argument to `al_copy_transform` is the target (https://liballeg.org/a5docs/trunk/transformations.html#al_copy_transform), so this will copy the zeroed `dest` to `t`.

**Comment by dradtke** [comment]
Fixed in https://github.com/dradtke/go-allegro/commit/84f79a58997bd961de8d1282940d6b32064765c9.
